name: Build

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
    inputs:
      release:
        description: 'Official release'
        required: false
        default: false
        type: boolean
  workflow_call:

jobs:
  set-envs:
    if: (github.event_name != 'schedule') || (github.repository == 'ROCKNIX/distribution' && github.ref_name == 'next')
    runs-on: ubuntu-24.04
    outputs:
      NIGHTLY: ${{ github.event_name == 'workflow_dispatch' && inputs.release == true && 'no' || 'yes' }}
      OFFICIAL: ${{ github.event_name == 'workflow_dispatch' && inputs.release == true && 'yes' || 'no' }}
      OWNER_LC: ${{ steps.set-envs.outputs.OWNER_OUTPUT }}
    steps:
      - name: Set lowercase owner name
        id: set-envs
        run: |
          OWNER_LC="${OWNER,,}"
          echo "OWNER_OUTPUT=${OWNER_LC}" >> $GITHUB_OUTPUT
        env:
          OWNER: ${{ github.repository_owner }}

  build-docker:
    if: (github.event_name != 'schedule') || (github.repository == 'ROCKNIX/distribution' && github.ref_name == 'next')
    name: Docker
    needs: set-envs
    uses: ./.github/workflows/build-docker-image.yml
    with:
      OWNER_LC: ${{ needs.set-envs.outputs.OWNER_LC }}

  build-devices:
    if: (github.event_name != 'schedule') || (github.repository == 'ROCKNIX/distribution' && github.ref_name == 'next')
    name: Build Devices
    needs:
      - set-envs
      - build-docker
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: RK3326
            project: ROCKNIX
#          - device: RK3399
#            project: ROCKNIX
#          - device: RK3566
#            project: ROCKNIX
#          - device: RK3588
#            project: ROCKNIX
#          - device: S922X
#            project: ROCKNIX
#          - device: H700
#            project: ROCKNIX
#          - device: SM8250
#            project: ROCKNIX
#          - device: SM8550
#            project: ROCKNIX
    uses: ./.github/workflows/build-device.yml
    secrets: inherit
    with:
      PROJECT: ${{ matrix.project }}
      DEVICE: ${{ matrix.device }}
      OWNER_LC: ${{ needs.set-envs.outputs.OWNER_LC }}
      NIGHTLY: ${{ needs.set-envs.outputs.NIGHTLY }}
      OFFICIAL: ${{ needs.set-envs.outputs.OFFICIAL }}

